// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Subscription struct {
	ID          uuid.UUID          `db:"id"`
	ServiceName string             `db:"service_name"`
	Price       int32              `db:"price"`
	UserID      uuid.UUID          `db:"user_id"`
	StartedAt   pgtype.Date        `db:"started_at"`
	EndedAt     pgtype.Date        `db:"ended_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at"`
}
