// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CalculateSubscriptionsTotal(ctx context.Context, arg CalculateSubscriptionsTotalParams) (int64, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	DeleteSubscription(ctx context.Context, id uuid.UUID) (int64, error)
	GetSubscriptionByID(ctx context.Context, id uuid.UUID) (Subscription, error)
	ListSubscriptions(ctx context.Context, arg ListSubscriptionsParams) ([]Subscription, error)
	UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error)
}

var _ Querier = (*Queries)(nil)
