// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const calculateSubscriptionsTotal = `-- name: CalculateSubscriptionsTotal :one
SELECT COALESCE(
    SUM(
        s.price::bigint * (
            (
                EXTRACT(YEAR FROM LEAST(COALESCE(s.ended_at, $1::date), $1::date))::bigint
                - EXTRACT(YEAR FROM GREATEST(s.started_at, $2::date))::bigint
            ) * 12
            + (
                EXTRACT(MONTH FROM LEAST(COALESCE(s.ended_at, $1::date), $1::date))::bigint
                - EXTRACT(MONTH FROM GREATEST(s.started_at, $2::date))::bigint
            ) + 1
        )
    ),
    0
)::bigint AS total
FROM subscriptions AS s
WHERE s.started_at <= $1::date
  AND COALESCE(s.ended_at, $1::date) >= $2::date
  AND ($3::uuid IS NULL OR s.user_id = $3::uuid)
  AND ($4::text IS NULL OR s.service_name = $4::text)
`

type CalculateSubscriptionsTotalParams struct {
	To          pgtype.Date `db:"to"`
	From        pgtype.Date `db:"from"`
	UserID      pgtype.UUID `db:"user_id"`
	ServiceName *string     `db:"service_name"`
}

func (q *Queries) CalculateSubscriptionsTotal(ctx context.Context, arg CalculateSubscriptionsTotalParams) (int64, error) {
	row := q.db.QueryRow(ctx, calculateSubscriptionsTotal,
		arg.To,
		arg.From,
		arg.UserID,
		arg.ServiceName,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    id,
    service_name,
    price,
    user_id,
    started_at,
    ended_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, service_name, price, user_id, started_at, ended_at, created_at, updated_at
`

type CreateSubscriptionParams struct {
	ID          uuid.UUID   `db:"id"`
	ServiceName string      `db:"service_name"`
	Price       int32       `db:"price"`
	UserID      uuid.UUID   `db:"user_id"`
	StartedAt   pgtype.Date `db:"started_at"`
	EndedAt     pgtype.Date `db:"ended_at"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.ID,
		arg.ServiceName,
		arg.Price,
		arg.UserID,
		arg.StartedAt,
		arg.EndedAt,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :execrows
DELETE FROM subscriptions
WHERE id = $1
`

func (q *Queries) DeleteSubscription(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSubscription, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, service_name, price, user_id, started_at, ended_at, created_at, updated_at
FROM subscriptions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, service_name, price, user_id, started_at, ended_at, created_at, updated_at
FROM subscriptions
WHERE ($1::uuid IS NULL OR user_id = $1::uuid)
  AND ($2::text IS NULL OR service_name = $2::text)
ORDER BY created_at DESC, id DESC
LIMIT $4
OFFSET $3
`

type ListSubscriptionsParams struct {
	UserID      pgtype.UUID `db:"user_id"`
	ServiceName *string     `db:"service_name"`
	Offset      int32       `db:"offset"`
	Limit       int32       `db:"limit"`
}

func (q *Queries) ListSubscriptions(ctx context.Context, arg ListSubscriptionsParams) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptions,
		arg.UserID,
		arg.ServiceName,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.ServiceName,
			&i.Price,
			&i.UserID,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE subscriptions
SET
    service_name = $1,
    price = $2,
    user_id = $3,
    started_at = $4,
    ended_at = $5,
    updated_at = NOW()
WHERE id = $6
RETURNING id, service_name, price, user_id, started_at, ended_at, created_at, updated_at
`

type UpdateSubscriptionParams struct {
	ServiceName string      `db:"service_name"`
	Price       int32       `db:"price"`
	UserID      uuid.UUID   `db:"user_id"`
	StartedAt   pgtype.Date `db:"started_at"`
	EndedAt     pgtype.Date `db:"ended_at"`
	ID          uuid.UUID   `db:"id"`
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscription,
		arg.ServiceName,
		arg.Price,
		arg.UserID,
		arg.StartedAt,
		arg.EndedAt,
		arg.ID,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
